### ISSUE TITLE
Gravar vídeo demonstrando a aplicação publicada na EKS

### ISSUE THREAD

**Issue by MauroImamura** [lanchesjaamp/dotlanche#34]

**Comment by atcorrea** [comment]
Dúvida enviada no discord:
https://discord.com/channels/1065992165232214066/1258552717924892725/1258552717924892725

**Comment by atcorrea** [comment]
Conteúdo do vídeo:

- Mostrar a api do projeto rodando dentro de um cluster kubernetes (local ou cloud), executar comandos no terminal para exibir os pods, services, hpa, etc. rodando.
- Realizar algumas chamadas no Postman mostrando o funcionamento da api, conforme as instruções que definimos.
- Execução de um teste que faça com que o número de pods aumente conforme demanda.
- Na parte de demostrar o código, deixe bem claro a separação das camadas, o não uso de frameworks nas camadas internas (core / regras de negócio), as interfaces e seus adaptadores.

**Comment by atcorrea** [comment]
Quanto ao tempo de duração do vídeo, resposta do professor:
`Oi André, na verdade não tem uma duração correta.. o importante é dar o máximo de informação para dar insumos para o professor avaliar, se conseguir fazer isso em 10 minutos, ok, se conseguir fazer isso em 30 minutos, ok tbm.`

**Comment by atcorrea** [comment]
Link do vídeo
https://www.youtube.com/watch?v=PfyiMBKDJ1Y
